// Mocks generated by Mockito 5.4.4 from annotations
// in worstmovie/test/data/usecases/get_producers_impl_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i4;

import 'package:dartz/dartz.dart' as _i2;
import 'package:mockito/mockito.dart' as _i1;
import 'package:worstmovie/core/errors/failure.dart' as _i5;
import 'package:worstmovie/data/repositories/producer_repository.dart' as _i3;
import 'package:worstmovie/domain/entities/producer.dart' as _i6;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeEither_0<L, R> extends _i1.SmartFake implements _i2.Either<L, R> {
  _FakeEither_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [ProducerRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockProducerRepository extends _i1.Mock
    implements _i3.ProducerRepository {
  @override
  _i4.Future<
      _i2.Either<_i5.Failure,
          Map<String, List<_i6.Producer>>>> getProducers() =>
      (super.noSuchMethod(
        Invocation.method(
          #getProducers,
          [],
        ),
        returnValue: _i4.Future<
                _i2.Either<_i5.Failure, Map<String, List<_i6.Producer>>>>.value(
            _FakeEither_0<_i5.Failure, Map<String, List<_i6.Producer>>>(
          this,
          Invocation.method(
            #getProducers,
            [],
          ),
        )),
        returnValueForMissingStub: _i4.Future<
                _i2.Either<_i5.Failure, Map<String, List<_i6.Producer>>>>.value(
            _FakeEither_0<_i5.Failure, Map<String, List<_i6.Producer>>>(
          this,
          Invocation.method(
            #getProducers,
            [],
          ),
        )),
      ) as _i4
          .Future<_i2.Either<_i5.Failure, Map<String, List<_i6.Producer>>>>);
}
